### ISSUE TITLE
索敌时出现异常情况

### ISSUE THREAD

**Issue by linhaiwen** [OpenWSGR/AutoWSGR#127]
![image](https://github.com/user-attachments/assets/99e0b23a-22c0-46a9-8910-7b479cc0db55)
在演习和大活动时会出现这个问题

**Comment by veadex** [comment]
这个代码并不会在演习时触发，能提供更多的信息吗？例如那个保存的图片

**Comment by linhaiwen** [comment]
![2024-12-22_09-52-46](https://github.com/user-attachments/assets/cb316c10-2313-4c40-a591-70f13488bb46)
[log_2024-12-22_09-52-21_074488.log](https://github.com/user-attachments/files/18221134/log_2024-12-22_09-52-21_074488.log)
[config.json](https://github.com/user-attachments/files/18221135/config.json)
好的，我都提交上来了

**Comment by veadex** [comment]
更新最新版
