### ISSUE TITLE
功能建议

### ISSUE THREAD

**Issue by veadex** [OpenWSGR/AutoWSGR#49]
建议添加满级自动换船的功能：
1. 建议将相关设置放在相应的`plan`里面，方便练级，练战术，5拖一分开
2. 希望尽可能的筛选舰船，例如我要切换切换为列克星敦，有满级的，有未满级的，可以使用游戏内的功能切换到未满级的舰船，或者搓一个等级识别，
3. 换船时可以考虑使用OCR识别舰船，如果要换船，可以先搜索，截图识别，根据设置筛选（例如cv-16筛选出90级以下），返回筛选后符合设置的第一个船的坐标
4. 如果有多个船的问题，例如我要练两个cv-16，第一个练完之后在数据中标记练完这个了，紧接着选第二个练，这两个船要区分开
5. 如果可以的话识别当前舰船，方便到一定等级停止，例如CV-16在9-3的养殖，希望到90级停止，
6. 如果有GUI的话相关配置就不会显得那么多

**Comment by linhaiwen** [comment]
> 1, 2, 3, 5 done [a191e6d](https://github.com/huan-yp/Auto-WSGR/commit/a191e6d146eb3af75e045661385480c933f90f16)

老哥，群里方便通过一下吗？方便说下隔多久会自动检查是否有完成的远征任务？

**Comment by linhaiwen** [comment]
> > > 1, 2, 3, 5 done [a191e6d](https://github.com/huan-yp/Auto-WSGR/commit/a191e6d146eb3af75e045661385480c933f90f16)
> > 
> > 
> > 老哥，群里方便通过一下吗？方便说下隔多久会自动检查是否有完成的远征任务？
> 
> 自动检查有参数可以设置： https://github.com/huan-yp/Auto-WSGR/blob/main/autowsgr/fight/common.py#L309 QQ群号：568500514 验证问题答案：战舰少女R

我申请了，但是到现在都没通过……

**Comment by veadex** [comment]
> > > > 1, 2, 3, 5 done [a191e6d](https://github.com/huan-yp/Auto-WSGR/commit/a191e6d146eb3af75e045661385480c933f90f16)
> > > 
> > > 
> > > 老哥，群里方便通过一下吗？方便说下隔多久会自动检查是否有完成的远征任务？
> > 
> > 自动检查有参数可以设置： https://github.com/huan-yp/Auto-WSGR/blob/main/autowsgr/fight/common.py#L309 QQ群号：568500514 验证问题答案：战舰少女R
> 
> 我申请了，但是到现在都没通过……

这边没收到过没通过的申请，你是不是加错群了
