### ISSUE TITLE
两个会让程序崩溃的bug

### ISSUE THREAD

**Issue by WinterRaurant** [OpenWSGR/AutoWSGR#69]
索敌失败直接进入阵型选择页面时有概率在 `autowsgr\fight\common.py` 的 `line269` 报 `autowsgr.constants.custom_exceptions.ImageNotFoundErr`
打开游戏进入点击“进入游戏”页面后有概率在 `autowsgr\utils\api_image.py` 的 `line24` 报 `AssertionError: abs_x and abs_y should be in [0, (720, 1280)]`，手动输出了一下此时的 `abs_x` 和 `abs_y` 分别是1137 和 623

**Comment by veadex** [comment]
能说一下你的模拟器的分辨率吗？

**Comment by 0xWelt** [comment]
久未更新
